Add clickToURL helper script.
kasenvr/project-athena pull request #587
Opened 2020-08-04 03:41 UTC by kasenvr

Will add to Inventory "Market" later.

2020-08-04 05:15 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e429cc3_531eeb01.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e429cc3.tar_531eeb01.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e429cc3.tar_531eeb01.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e429cc3_531eeb01.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e429cc3_531eeb01.exe

2020-08-05 23:44 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-5d5c72b_46995676.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-5d5c72b.tar_46995676.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-5d5c72b.tar_46995676.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-5d5c72b_46995676.exe

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-5d5c72b_46995676.dmg

2020-08-06 02:24 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-dabbb7f_02401073.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-dabbb7f.tar_02401073.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-dabbb7f.tar_02401073.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-dabbb7f_02401073.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-dabbb7f_02401073.exe

2020-08-09 00:03 UTC, ctrlaltdavid commented on unpublishedScripts/clickToURL.js
> +    clickToOpen.js
```suggestion
    clickToURL.js
```

2020-08-09 00:08 UTC, ctrlaltdavid commented on unpublishedScripts/domainUserCount.js
> +        timer = Script.setInterval(function () {
It would be better to use `Script.setTimeout()` so that when the entity server gets overloaded, timer events don't piile up.

2020-08-09 00:08 UTC, ctrlaltdavid commented on unpublishedScripts/domainUserCount.js
> +});
Missing CR at end of file.

2020-08-09 00:09 UTC, ctrlaltdavid commented on unpublishedScripts/domainUserCount.js
> +    var UPDATE_INTERVAL = 1000; // 1 second
An update every second may be too often in domains expecting lots of avatars?

2020-08-09 00:10 UTC, ctrlaltdavid commented on unpublishedScripts/clickToURL.js
> +});
Missing CR and end of file.

2020-08-09 00:10 UTC, ctrlaltdavid commented on unpublishedScripts/clickToURL.js
> +        if (_this.entityID == pressedEntityID) {
```suggestion
        if (_this.entityID === pressedEntityID) {
```

2020-08-20 21:26 UTC, JulianGro commented
Does clickToURL.js work with VR? It talks about `onMousePressOnEntity` in the script.

2020-08-24 22:03 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-43293b4.tar_c214fcf4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-43293b4.tar_c214fcf4.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-43293b4_c214fcf4.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-43293b4_c214fcf4.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-43293b4_c214fcf4.exe

2020-08-25 00:27 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-78fab0d_efbd9206.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-78fab0d_efbd9206.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-78fab0d.tar_efbd9206.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-78fab0d.tar_efbd9206.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-78fab0d_efbd9206.exe

2020-08-25 03:18 UTC, ctrlaltdavid requested changes

2020-08-25 03:18 UTC, ctrlaltdavid commented on unpublishedScripts/domainUserCount.js
> +
Should probably stop the timeout timer in here.

2020-08-25 04:54 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e523d0b.tar_dcbc0eb4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e523d0b_dcbc0eb4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e523d0b.tar_dcbc0eb4.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e523d0b_dcbc0eb4.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR587/Vircadia-Alpha-PR587-e523d0b_dcbc0eb4.exe

2020-08-25 19:10 UTC, ctrlaltdavid approved these changes

2020-09-01 22:50 UTC, kasenvr commented
These scripts should go in the vircadia-content repo. :)

2020-09-01 22:50 UTC, closed without merging