Playing with GHA
kasenvr/project-athena pull request #615
Opened 2020-08-11 22:52 UTC by HifiExperiments

2020-08-15 05:48 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-ea0b083.tar_62d12a5c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-ea0b083_62d12a5c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-ea0b083.tar_62d12a5c.Z

2020-08-15 19:49 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-87fb0e9_0fe340ec.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-87fb0e9_0fe340ec.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-87fb0e9.tar_0fe340ec.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-87fb0e9.tar_0fe340ec.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-87fb0e9_0fe340ec.exe

2020-08-15 21:48 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a8735fe_df84a3be.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a8735fe.tar_df84a3be.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a8735fe.tar_df84a3be.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a8735fe_df84a3be.dmg

2020-08-16 00:29 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-28905df.tar_e46156b7.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-28905df_e46156b7.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-28905df.tar_e46156b7.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-28905df_e46156b7.exe

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-28905df_e46156b7.dmg

2020-08-16 17:24 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-0a529a5.tar_7acda085.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-0a529a5.tar_7acda085.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-0a529a5_7acda085.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-0a529a5_7acda085.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-0a529a5_7acda085.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-0a529a5_7acda085.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-0a529a5_7acda085.exe

2020-08-17 00:33 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4292c31_ddc03924.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4292c31.tar_ddc03924.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4292c31.tar_ddc03924.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4292c31_ddc03924.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4292c31_ddc03924.exe

2020-08-20 01:41 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4c4776a.tar_b4609142.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4c4776a.tar_b4609142.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4c4776a_b4609142.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4c4776a_b4609142.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4c4776a_b4609142.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-4c4776a_b4609142.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-4c4776a_b4609142.apk

2020-08-20 04:55 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-df39eb1.tar_91a35fb4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-df39eb1_91a35fb4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-df39eb1.tar_91a35fb4.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-df39eb1_91a35fb4.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-df39eb1_91a35fb4.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-df39eb1_91a35fb4.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-df39eb1_91a35fb4.exe

2020-09-09 18:28 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a954443.tar_f453969c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a954443_f453969c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a954443.tar_f453969c.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a954443_f453969c.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a954443_f453969c.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-a954443_f453969c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-a954443_f453969c.apk

2020-09-29 14:26 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-247338d.tar_f453969c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-247338d.tar_f453969c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-247338d_f453969c.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-247338d_f453969c.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-247338d_f453969c.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-247338d_f453969c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-247338d_f453969c.apk

2020-10-12 01:47 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-3d45573.tar_f453969c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-3d45573.tar_f453969c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-3d45573_f453969c.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-3d45573_f453969c.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-3d45573_f453969c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-3d45573_f453969c.apk

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-3d45573_f453969c.dmg

2020-10-13 07:49 UTC, ctrlaltdavid commented on scripts/system/quickGoto.js
> +    addGotoButton("167.172.61.134");
Can more human-friendly addresses be used instead of hard-coded IP addresses?

2020-10-29 21:20 UTC, kasenvr requested changes

2020-10-29 21:20 UTC, kasenvr commented on scripts/system/quickGoto.js
> +    addGotoButton("172.104.248.237");
```suggestion
    addGotoButton("hub.daleglass.net");
```

2020-10-29 21:20 UTC, kasenvr commented on scripts/system/quickGoto.js
> +    addGotoButton("167.172.61.134");
```suggestion
    addGotoButton("lq-hub.vircadia.com");
```

2020-10-31 00:51 UTC, ctrlaltdavid commented on scripts/system/quickGoto.js
> +    addGotoButton("167.172.61.134");
Thanks for the new URLs.

2020-10-31 00:52 UTC, ctrlaltdavid approved these changes

2020-10-31 01:13 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e3f37f6.tar_cec0b410.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e3f37f6.tar_cec0b410.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e3f37f6_cec0b410.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e3f37f6_cec0b410.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e3f37f6_cec0b410.exe

2020-10-31 01:35 UTC, HifiExperiments commented
hm looks like the automatic texture PR broke android builds

2020-11-07 22:57 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-7915cf0.tar_cec0b410.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-7915cf0.tar_cec0b410.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-7915cf0_cec0b410.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-7915cf0_cec0b410.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-7915cf0_cec0b410.exe

2020-11-10 05:13 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-138d861.tar_b6d53192.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-138d861_b6d53192.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-138d861.tar_b6d53192.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-138d861_b6d53192.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-138d861_b6d53192.exe

2020-11-10 05:36 UTC, HifiExperiments commented
@daleglass I basically had to just disable the automatic texture memory detection on android and quest because it seems the GL extensions won't work there.  correct me if I'm wrong, but it seems like this would effectively change nothing, since they would have just been falling back to the old method anyways?

2020-11-10 07:26 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e8811f1.tar_696239a9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e8811f1.tar_696239a9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e8811f1_696239a9.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e8811f1_696239a9.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e8811f1_696239a9.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-e8811f1_696239a9.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-e8811f1_696239a9.apk

2020-11-17 22:45 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-echo 6fd6a47cc6e2873e84a33508d9f0d88814f8dbe0 | cut -c1-7_be55993d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-echo 6fd6a47cc6e2873e84a33508d9f0d88814f8dbe0 | cut -c1-7.tar_be55993d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-echo 6fd6a47cc6e2873e84a33508d9f0d88814f8dbe0 | cut -c1-7.tar_be55993d.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-echo 6fd6a47cc6e2873e84a33508d9f0d88814f8dbe0 | cut -c1-7_be55993d.dmg

2020-11-18 20:58 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-15da7ba.tar_1e07971d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-15da7ba_1e07971d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-15da7ba.tar_1e07971d.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-15da7ba_1e07971d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-15da7ba_1e07971d.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-15da7ba_1e07971d.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-15da7ba_1e07971d.apk

2020-11-19 03:24 UTC, ctrlaltdavid approved these changes

2020-11-19 04:11 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-8db0f10_80478876.apk

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.dmg

2020-11-19 07:25 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.exe

2020-11-19 09:26 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.exe

2020-11-19 23:56 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10.tar_80478876.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Quest-Alpha-PR615-8db0f10_80478876.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR615/Vircadia-Alpha-PR615-8db0f10_80478876.apk

2020-11-19 23:57 UTC, kasenvr commented
Looks like we got our Android builds!

2020-11-20 05:36 UTC, kasenvr approved these changes
Tested the latest Windows build generated from this PR and it worked well.

2020-11-24 23:42 UTC, merged