Update OSX folder icons to Vircadia.
kasenvr/project-athena pull request #653
Opened 2020-08-25 07:27 UTC by kasenvr

(p.s. I didn't actually check to see if this works, but I assume it did!)

2020-08-25 09:12 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-e89cf87.tar_9f810700.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-e89cf87_9f810700.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-e89cf87.tar_9f810700.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-e89cf87_9f810700.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-e89cf87_9f810700.exe

2020-08-26 18:04 UTC, kasenvr commented
![image](https://user-images.githubusercontent.com/52365539/91339815-048a1600-e7a5-11ea-8d8f-3d2c00f5cbd9.png)
Can confirm, she did work. :)

2020-08-26 18:18 UTC, yuriymacdev requested changes

2020-08-26 18:18 UTC, yuriymacdev commented on BUILD_OSX.md
> +    sudo cmake ../ -DCMAKE_OSX_SYSROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DOPENSSL_ROOT_DIR=/us
I think sudo here is redundant

2020-08-26 18:18 UTC, yuriymacdev commented on BUILD_OSX.md
>  If the build completes successfully, you will have built targets for all components located in the `build/${target_name}/Debug` directories.
Due to a naming conflict (one of the app's libs has a name libgl which is the same as one of the OSX frameworks), running from Xcode raises runtime error (building is fine though).

2020-08-26 18:18 UTC, yuriymacdev commented on BUILD_OSX.md
> +You will need version `10.12` of the OSX SDK for building. You can get that from [here](https://github.com/phracker/MacOSX-SDKs). You must copy it in to your Xcode SDK directory, e.g.
Perhaps it makes sense to add here a short explanation why newer sdks fail and with what error, so the issue is searchable by those who try to build it and see the runtime crashes.

2020-08-26 20:08 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-0e1790a.tar_374b3653.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-0e1790a_374b3653.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-0e1790a.tar_374b3653.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-0e1790a_374b3653.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-0e1790a_374b3653.exe

2020-08-27 10:37 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-bad7f35.tar_fabf8e98.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-bad7f35_fabf8e98.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-bad7f35.tar_fabf8e98.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-bad7f35_fabf8e98.exe

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR653/Vircadia-Alpha-PR653-bad7f35_fabf8e98.dmg

2020-08-29 05:20 UTC, ArcadeFever commented
Ahah! I knew the icon was in one of those .rsrc files!  Can I ask what utility you used to extract and replace the icon files with?

2020-09-02 06:16 UTC, kasenvr commented
Alright, I opened an issue for that so we can go ahead with this and do that later. :) Thank you!

2020-09-03 01:54 UTC, merged