Feature/require redownload
kasenvr/project-athena pull request #664
Opened 2020-08-30 19:03 UTC by kasenvr

Require will now have an option to clear the cache on a dependency when loading it. (effectively cachebusting it, officially...)

This PR is based on #658, so that must be merged first.

2020-08-30 20:54 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-cf81af1_d20295c4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-cf81af1.tar_d20295c4.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-cf81af1.tar_d20295c4.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-cf81af1_d20295c4.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-cf81af1_d20295c4.exe

2020-09-07 04:08 UTC, ctrlaltdavid requested changes

2020-09-07 04:08 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptEngine.h
> +     * @param {bool} [forceRedownload=false] - Invalidate the cache for this module and redownload it if necessary.
```suggestion
     * @param {boolean} [forceRedownload=false] - Invalidate the cache for this module and redownload it if necessary.
```

2020-09-07 05:36 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-d5eceb8.tar_d25adf9b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-d5eceb8.tar_d25adf9b.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-d5eceb8_d25adf9b.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-d5eceb8_d25adf9b.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-d5eceb8_d25adf9b.exe

2020-09-07 05:36 UTC, HifiExperiments commented on libraries/script-engine/src/ScriptEngine.cpp
> +    bool invalidateCache = (module.isUndefined() && cacheMeta.property(moduleId).isValid()) || forceRedownload;
```suggestion
    bool invalidateCache = forceRedownload || (module.isUndefined() && cacheMeta.property(moduleId).isValid());
```
this way the code can short circuit and save us some work

2020-09-07 07:16 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-824de17.tar_8a007a4e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-824de17_8a007a4e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-824de17.tar_8a007a4e.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-824de17_8a007a4e.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-824de17_8a007a4e.exe

2020-09-07 20:08 UTC, ctrlaltdavid approved these changes

2020-09-17 14:40 UTC, vegaslon commented
After talking with implementer of script.require it was suggested that this functionality be implemented as a developer scripting toggle so that it is infinitely more useful and does not require changing java script just to activate and deactivate the cache busting. such as Developer -> Scripting -> Disable Script.require cache. There is already ways to cache bust require before this pr and so if we are going for easy I think that option would be better since it is what web browsers do already for developement.

2020-09-18 00:05 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-7e8dda1.tar_9f3978d3.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-7e8dda1_9f3978d3.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-7e8dda1.tar_9f3978d3.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-7e8dda1_9f3978d3.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-7e8dda1_9f3978d3.exe

2020-10-10 07:10 UTC, ctrlaltdavid requested changes
Also, copyrights need to be added to Menu.cpp, Menu.h, and ScriptEngihe.h.

2020-10-10 07:10 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptEngine.cpp
> +    // Check to see if
Check to see if ... what?

2020-10-11 05:56 UTC, ctrlaltdavid approved these changes

2020-10-11 06:42 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-468a20a.tar_05ad3008.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-468a20a_05ad3008.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-468a20a.tar_05ad3008.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-468a20a_05ad3008.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-468a20a_05ad3008.exe

2020-10-28 11:47 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-4d53c34.tar_05ad3008.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-4d53c34_05ad3008.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-4d53c34.tar_05ad3008.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-4d53c34_05ad3008.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-4d53c34_05ad3008.exe

2020-11-05 22:25 UTC, kasenvr commented
Confirm this works over HTTP.

2020-11-05 23:06 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-6450e07.tar_05ad3008.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-6450e07_05ad3008.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-6450e07.tar_05ad3008.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-6450e07_05ad3008.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR664/Vircadia-Alpha-PR664-6450e07_05ad3008.exe

2020-11-12 06:32 UTC, kasenvr commented
Confirmed working over HTTP.

2020-11-12 22:10 UTC, merged