Remove "Console" options from Interface-only installer
kasenvr/project-athena pull request #682
Opened 2020-09-04 23:39 UTC by ctrlaltdavid

The advanced tab of the Windows Interface-only installer had three "console" advanced install options. These related to a cut-down version of the Sandbox's Windows system tray icon, with only some of the menu items such as "GoTo" - but these currently don't work properly. The "console" were not enabled by default in the advanced installer and were not enabled in the express install.

This PR temporarily removes the three "console" options from the Interface-only advanced install options - until such time as the "console" is fixed (and perhaps renamed) or it's decided it should be removed permanently.

2020-09-04 23:52 UTC, ctrlaltdavid commented
### Testing

Build 2 installers:
- Interface-only
- Interface + Sandbox

The Interface-only installer shoudl be smaller than the Interface + Sandbox installer.

Test Interface-only installer:
- Express install works:
  - Installs Interface.
  - Doesn't install domain server - domain-server.exe is not present in the install directory.
  - Interface runs.
- Custom install works:
  - There are no "Console" checkbox items present in the advanced options.
  - Installs Interface.
  - Doesn't install domain server - domain-server.exe is not present in the install directory.
  - Interface runs.

Test Interface + Sandbox installer:
- The 3 "Sandbox" checkbox items are present.
- Express install works as expected.
- Custom install works as expected. In parficular, the Sandbox server is installed or not installed, and run or not run, per checkbox items.

2020-09-05 01:31 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-10ff14a.tar_e2ffde22.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-10ff14a.tar_e2ffde22.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-10ff14a_e2ffde22.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-10ff14a_e2ffde22.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-10ff14a_e2ffde22.exe

2020-09-13 22:33 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-63ba953.tar_a3512d8a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-63ba953.tar_a3512d8a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-63ba953_a3512d8a.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-63ba953_a3512d8a.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-63ba953_a3512d8a.exe

2020-09-27 19:13 UTC, ctrlaltdavid commented
Raised at a recent dev/community meeting: how to notify people if they have a message or something while Interface is minimized. The Console app has this sort of functionality. Perhaps the Console app should be fixed / improved (and perhaps renamed to something more fitting).

2020-10-03 08:03 UTC, kasenvr commented
Will test this after https://github.com/kasenvr/project-athena/pull/651 is merged.

2020-10-10 05:02 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-3724219.tar_a3512d8a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-3724219_a3512d8a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-3724219.tar_a3512d8a.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-3724219_a3512d8a.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR682/Vircadia-Alpha-PR682-3724219_a3512d8a.exe

2020-10-10 05:42 UTC, kasenvr commented
![image](https://user-images.githubusercontent.com/52365539/95646771-bcdff500-0a99-11eb-8c9d-e7f16638863e.png)
So the interface + sandbox install worked fine, but I guess I should have tried the Interface only first... still seems to show the checkboxes.

2020-10-17 13:27 UTC, daleglass requested changes

2020-10-17 13:27 UTC, daleglass commented on cmake/templates/NSIS.template.in
> +  ; !insertmacro SetInstallOption $DesktopConsoleCheckbox @CONSOLE_DESKTOP_SHORTCUT_REG_KEY@ ${BST_UNCHECKED}
If we're removing things, why is there a whole bunch of  commented out code being added? Did something go wrong during a merge?

2020-10-17 23:35 UTC, ctrlaltdavid commented on README.md
> +[For Windows](https://github.com/kasenvr/project-athena/blob/master/INSTALLER.md)
Also in this PR, INSTALL.md is renamed to INSTALLER.md.

2020-10-17 23:41 UTC, daleglass commented on README.md
> +[For Windows](https://github.com/kasenvr/project-athena/blob/master/INSTALLER.md)
Oops, missed that. Ok.

2020-10-18 01:29 UTC, ctrlaltdavid commented
This PR is very old. I'm going to redo it from latest master.

2020-10-18 01:29 UTC, closed without merging