Update API docs to specify entity-server-script findEntities caveat.
kasenvr/project-athena pull request #789
Opened 2020-10-08 00:41 UTC by kasenvr

Related to helping address https://github.com/kasenvr/project-athena/issues/786 by mentioning the issue.

2020-10-08 03:15 UTC, HifiExperiments commented on libraries/entities/src/EntityScriptingInterface.h
> +     * running on them. You can apply a dummy script to entities that you would like found in a search.</p>
and descendants of entities with server scripts

2020-10-08 21:06 UTC, ctrlaltdavid requested changes

2020-10-08 21:06 UTC, ctrlaltdavid commented on libraries/entities/src/EntityScriptingInterface.h
> +     * running on them. You can apply a dummy script to entities that you would like found in a search.</p>
```suggestion
     * <p><strong>Note:</strong> Server entity scripts only find entities that have a server entity script
     * running in them or a parent entity. You can apply a dummy script to entities that you want found in a search.</p>
```
Ditto for other occurrences.

2020-10-09 06:33 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR789/Vircadia-Alpha-PR789-a8b3896_af8ee998.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR789/Vircadia-Alpha-PR789-a8b3896.tar_af8ee998.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR789/Vircadia-Alpha-PR789-a8b3896.tar_af8ee998.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR789/Vircadia-Alpha-PR789-a8b3896_af8ee998.exe

2020-10-09 06:44 UTC, ctrlaltdavid approved these changes

2020-10-13 09:20 UTC, merged