First run script.
kasenvr/project-athena pull request #805
Opened 2020-10-12 20:45 UTC by kasenvr

This script will have things to run on first run, the first of which is a prompt to ask the user to set a display name.

2020-10-12 21:17 UTC, ctrlaltdavid commented
Only prompt for display name if one isn't already set?

2020-10-12 22:18 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-d7b4696.tar_4154e16f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-d7b4696.tar_4154e16f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-d7b4696_4154e16f.sh

2020-10-12 23:54 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8c6f504_58cfb75d.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8c6f504.tar_58cfb75d.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8c6f504.tar_58cfb75d.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8c6f504_58cfb75d.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8c6f504_58cfb75d.exe

2020-10-13 08:33 UTC, ctrlaltdavid requested changes

2020-10-13 08:33 UTC, ctrlaltdavid commented on scripts/system/onFirstRun.js
> +    var SETTING_TO_CHECK = 'firstRun';
Unused variable, `SETTING_TO_CHECK`.

2020-10-13 08:33 UTC, ctrlaltdavid commented on scripts/system/onFirstRun.js
> +    if ((Settings.getValue('firstRun', false) && MyAvatar.displayName === '') || MyAvatar.displayName === '') {
```suggestion
    if (!Settings.getValue('firstRun', false)) {
        return;
    }
    
    if (MyAvatar.displayName === '') {
```

2020-10-13 08:33 UTC, ctrlaltdavid commented on scripts/system/onFirstRun.js
> +    var DEFAULT_NAME = '';
```suggestion
    var DEFAULT_DISPLAY_NAME = '';
```
More descriptive name just in case some other name item is added to the script in the future.

2020-10-13 10:36 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-cee414e.tar_4dd1026e.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-cee414e_4dd1026e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-cee414e.tar_4dd1026e.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-cee414e_4dd1026e.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-cee414e_4dd1026e.exe

2020-10-13 19:51 UTC, ctrlaltdavid requested changes

2020-10-13 19:51 UTC, ctrlaltdavid commented on scripts/system/onFirstRun.js
> +            MyAvatar.displayName = DEFAULT_NAME;
```suggestion
            MyAvatar.displayName = DEFAULT_DISPLAY_NAME;
```

2020-10-13 19:53 UTC, ctrlaltdavid approved these changes

2020-10-13 21:23 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8344fce_2777854e.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8344fce.tar_2777854e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8344fce_2777854e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8344fce.tar_2777854e.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR805/Vircadia-Alpha-PR805-8344fce_2777854e.exe

2020-10-13 22:27 UTC, kasenvr commented
Played with it a bit post-CR, generally seems to work as expected.

2020-10-15 21:13 UTC, merged