Prevent crash on entity-script-server for due to logging interface.
kasenvr/project-athena pull request #840
Opened 2020-10-25 22:36 UTC by kasenvr

I've confirmed this fixes the issue.

2020-10-25 22:54 UTC, daleglass approved these changes

2020-10-25 23:47 UTC, ctrlaltdavid requested changes

2020-10-25 23:47 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptEngine.cpp
>      if (loggerInterface->showSourceDebugging()) {
```suggestion
    if (loggerInterface && loggerInterface->showSourceDebugging()) {
```
This should work, I think, and will `scriptEngine->print()` the message and `qCDebug()` the message with the filename.

2020-10-26 00:10 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c2efe34.tar_50067e33.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c2efe34.tar_50067e33.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c2efe34_50067e33.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c2efe34_50067e33.dmg

2020-10-26 01:40 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c8694e2.tar_4b2c71cf.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c8694e2_4b2c71cf.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c8694e2.tar_4b2c71cf.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c8694e2_4b2c71cf.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR840/Vircadia-Alpha-PR840-c8694e2_4b2c71cf.exe

2020-10-26 03:04 UTC, kasenvr commented
Twa_hinkle has confirmed that this solves the issue for him.

2020-10-26 03:09 UTC, merged