ScriptCache: add local file change
kasenvr/project-athena pull request #848
Opened 2020-10-29 17:40 UTC by humbletim

This PR helps ScriptCache detect local file changes.

Before, when working on Client Scripts that rely on `Script.require` to load modules in, it was virtually impossible to cache-bust those inner file dependencies.

With this PR reloading a Client Script will pick up any local changes automatically.

Note that I also considered just never caching local script paths ever -- however, in my case URLs that look like local files might actually be across network shares; so, by actually checking the modification time here, ScriptCache continues to work well in those scenarios too. 

### Test Plan

**Setup**: Create these two .js scripts in a local folder:
```js
// client-test.js
Script.require('./show-alert.js')
```
```js
// show-alert.js
Window.alert('“Um.” —First horse that got ridden');
```
1) Use Running Scripts... to load `client-test.js`
    - you should see the alert
2) Reload `client-test.js`
    - you should see the alert; and in the main app log:
    `[DEBUG] [hifi.scriptengine] Found script in cache: "show-alert.js"`
3) Make an external change to `show-alert.js` (eg: modify the message and resave).
4) Reload `client-test.js`
    - you should see the alert; and in the main app log:
    `[DEBUG] [hifi.scriptengine] Found script in cache, but local file modified; reloading: "show-alert.js" (memory: "Thu, 29 Oct 2020 10:47:30 GMT" disk: "Thu, 29 Oct 2020 11:22:40 GMT" )`
5) (without changing anything) Reload `client-test.js` again:
    - you should see the alert; and in the main app log:
    `[DEBUG] [hifi.scriptengine] Found script in cache: "show-alert.js"`

//

2020-10-31 01:39 UTC, ctrlaltdavid requested changes

2020-10-31 01:39 UTC, ctrlaltdavid commented on libraries/networking/src/ResourceRequest.cpp
> +        .toLatin1();
```suggestion
    return QDateTime::fromMSecsSinceEpoch(msecsSinceEpoch)
        .toString("ddd, dd MMM yyyy hh:mm:ss 'GMT'")
        .toLatin1();
```
Would something like this be simpler?

2020-10-31 01:39 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptCache.cpp
> +            auto mtime = QFileInfo(url.toLocalFile()).lastModified();
`modifiedTime` would be a preferable variable name.

2020-10-31 01:39 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptCache.cpp
> +          return;
Indenting.

2020-10-31 01:39 UTC, ctrlaltdavid commented on libraries/script-engine/src/ScriptCache.cpp
> +                  { "last-modified", req->property("last-modified") },
Indenting.

2020-10-31 19:26 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR848/Vircadia-Alpha-PR848-aab8a63_f41ef31e.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR848/Vircadia-Alpha-PR848-aab8a63.tar_f41ef31e.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR848/Vircadia-Alpha-PR848-aab8a63.tar_f41ef31e.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR848/Vircadia-Alpha-PR848-aab8a63_f41ef31e.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR848/Vircadia-Alpha-PR848-aab8a63_f41ef31e.exe

2020-11-01 01:50 UTC, ctrlaltdavid approved these changes

2020-11-05 22:02 UTC, kasenvr approved these changes
Worked as expected for me!

2020-11-05 22:20 UTC, merged