Create App. - Feature Bundle - Nov 2020
kasenvr/project-athena pull request #858
Opened 2020-11-11 04:14 UTC by AleziaKurdis

Contains:

1- **Entity List - Highlighting of the Last Selected entity**
The last selected entity is now displayed in darker blue in the list (if present per radius search)
This makes clearer which entity could become the parent.

2- Columns **visibility** and **order** are now **persistent**.

3- For clarity, "**Select Family**" and "**Select Top Family**" have been **renamed** respectively:
"**Select Parent And All Its Children**" and "**Select Top Parent And All Its Children**"

4- **New in-world bounding box color for a selected entity that is Parent & Child at the same time.**
When 1 entity is selected (in-world):
if the entity is a **Top Parent**, the selection color of the bounding box is **Orange**.
if the entity is **Parent and Child**, the selection color of the bounding box is **Majenta**. <=NEW!
if the entity is only a **Child**, then the selection color of the bounding box is **Cyan**.
If not involved in any parent line, or if the selection is multiple, then the selection color of the bounding box is **Light Grey**.

5- **Bug fix**: The "Selection" and "Actions" menu now close when we close the Entity list window or the Create App.

6- **Bug fix**: “Move Selected Entities to Avatar” is now recorded in the undo history. So undo/redo can be done.

7- **Bug fix**: EntityList, CTRL-Click was adding the last selected entity as the first selection the selection stack. The first selected item was systematically the last item of the selection. This was causing unpredictable results with "Parent Entities To The Last Selected". (This bug becomes evident by highlighting the "Last Selected" in the entity list.

2020-11-11 04:17 UTC, AleziaKurdis commented
Please, **Do Not Merge** now.
I still have some planned stuff for this bundle.
_(But note that what is in this PR if fully functional as it is)_

2020-11-11 09:17 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-dbbae4d_38e15b62.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-dbbae4d.tar_38e15b62.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-dbbae4d_38e15b62.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-dbbae4d.tar_38e15b62.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-dbbae4d_38e15b62.exe

2020-11-12 04:48 UTC, AleziaKurdis commented
8- Add a new User Preference for the Default value of the Entity List Radius. This is available in the Edit menu. If changed, this value will be used as the default Radius for the next time the script will be loaded.

9- Changed the label for "URL of a .json to import" in "Edit > Import Entities from URL". (it was previously "URL of SVO to Import", SVO being replaced by json long time ago.)

2020-11-12 06:34 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8e08e7f_7bec7cba.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8e08e7f_7bec7cba.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8e08e7f.tar_7bec7cba.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8e08e7f.tar_7bec7cba.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8e08e7f_7bec7cba.exe

2020-11-12 23:26 UTC, Aitolda commented
For some reason I get no loading dialogue when using this build, although worlds still seem to be loading fine.  Not sure what to make of this.

2020-11-13 04:57 UTC, AleziaKurdis commented
10- The action “**Import Entities (.json) from a URL**” has been added to the “**Create**” **Tab**. (It was available only in the Edit menu.)
![image](https://user-images.githubusercontent.com/60075796/99030181-648d8e80-2542-11eb-9904-a941edd69cf8.png)

11- The Create App. **Menu Items** under the “**Edit**” menu have been cleaned up.
All the actions, being transferred to the Create App. UI, has been removed. (Some was not even decently usable from there, mainly in HMD.)
A new-sub menu “**Create Application – Preferences**” has been implemented to regroup the remaining menu items that are all **User Preferences**. 
![image](https://user-images.githubusercontent.com/60075796/99030340-be8e5400-2542-11eb-9119-84a724008390.png)

Eventually in the future, these might be moved to the Create App. UI. For now, it will be OK, it's already cleaner.

2020-11-13 06:27 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-0508efc_e0cac2b9.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-0508efc.tar_e0cac2b9.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-0508efc.tar_e0cac2b9.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-0508efc_e0cac2b9.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-0508efc_e0cac2b9.exe

2020-11-13 06:53 UTC, Aitolda commented
[if the entity is Parent and Child, the selection color of the bounding box is Majenta](https://i.gyazo.com/32e2da10e556f01dacf907af14a5a7e1.png)

This doesn't seem to be working. I still get grey.

2020-11-13 15:16 UTC, AleziaKurdis commented
> [if the entity is Parent and Child, the selection color of the bounding box is Majenta](https://i.gyazo.com/32e2da10e556f01dacf907af14a5a7e1.png)
> 
> This doesn't seem to be working. I still get grey.

In you screenshot, you have a multiple selection. 
The box will be light gray for multiple selection, since it can be a collection of different hierarchies.

The color will be applicable only on a single selection.
It's mainly there to give a minimal feedback about the patent state of what is selected.
so you can figure if it's a Top Parent (orange), just a parent inside a hierarchy(majenta), a child (cyan), or not involved in any hierarchy (light gray)

2020-11-13 16:04 UTC, Aitolda commented
> > [if the entity is Parent and Child, the selection color of the bounding box is Majenta](https://i.gyazo.com/32e2da10e556f01dacf907af14a5a7e1.png)
> > This doesn't seem to be working. I still get grey.
> 
> In you screenshot, you have a multiple selection.
> The box will be light gray for multiple selection, since it can be a collection of different hierarchies.
> 
> The color will be applicable only on a single selection.
> It's mainly there to give a minimal feedback about the patent state of what is selected.
> so you can figure if it's a Top Parent (orange), just a parent inside a hierarchy(majenta), a child (cyan), or not involved in any hierarchy (light gray)

Ok.  I misunderstood. I took it to mean that if you had both a parent and a child selected it would be magenta.  Now I realize you meant a single entity which is both a parent and a child, in the middle of the hierarchy.

2020-11-14 03:46 UTC, AleziaKurdis commented
That will be that for this feature bundle.
**It can be merged, once reviewed, tested, accepted.**

**KNOWN ISSUES:**
**#861 Menu.addMenuItem can't position item over existing ones in HMD Tablet Menu**
_This makes "Undo" and "Redo" to appear at the end of the "Edit" menu in HDM Tablet Menu only. The issue was present before this current PR. So the current script is expected to be right, but there is a bug somewhere in the code side._
Severity: Low
Priority: Low

2020-11-14 19:17 UTC, Aitolda commented
It's working fantastic for me.  Using it currently for a build!

2020-11-15 03:21 UTC, ctrlaltdavid requested changes

2020-11-15 03:21 UTC, ctrlaltdavid commented on scripts/system/create/entityList/html/entityList.html
> +            </button>
Extraneous spaces.

2020-11-15 03:21 UTC, ctrlaltdavid commented on scripts/system/create/entityList/html/js/entityList.js
> +                                        swapColumns(i-1, i);
```suggestion
                                        swapColumns(i - 1, i);
```
And similarly in the next two lines.

2020-11-15 03:21 UTC, ctrlaltdavid commented on scripts/system/create/qml/EditToolsTabView.qml
> +                        anchors.rightMargin: 10
Extraneous spaces.

2020-11-15 04:36 UTC, ctrlaltdavid approved these changes

2020-11-15 05:32 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8f9a1d2_da2737de.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8f9a1d2.tar_da2737de.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8f9a1d2.tar_da2737de.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8f9a1d2_da2737de.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR858/Vircadia-Alpha-PR858-8f9a1d2_da2737de.exe

2020-11-16 04:01 UTC, merged

2020-11-18 13:15 UTC, vegaslon commented
QA Missed the removal or export entity from this PR.

2020-11-18 20:44 UTC, Aitolda commented
> QA Missed the removal of export entity from the menu and no addition of it to the create app.

Export can be found at the bottom of the entity list.