Fix for Issue #869
kasenvr/project-athena pull request #874
Opened 2020-11-19 04:28 UTC by AleziaKurdis

Fix for Issue #869

This excludes the local and avatar entities from what is returns by Entities.getChildrenIDs
to avoid the selection tools of the Zone entities to be considered as Children of it.
This was necessary for the display of the hierarchy status, but also for the "Add Children to Selection".

**For the QA:**
1- Open the "Create" Application
2- Make sure to have the "Hierarchy" column displayed in the entity list.
3- Create a new Zone entity
**Before this fix:**
The new zone entity was displayed as being a Top Parent. (because there was a local entity parented to it. (to display the grid box)
In In-world view, the bounding box was also indicating that it was a Top Parent (it was displayed in Orange instead of light gray)
If you selected that new zone, and do "**Selection... > Add Children to Selection**", the bounding box turned light gray as a multiple selection. If you were keeping CTRL pressed and deselect the zone only, then you could see the invisible local entity selected with a bounding box in cyan (as a child).

**After this fix:**
No more trace of any children, since local entities are now ignored when we get the list of the children.
So new zones are no more displayed as a Parent of a child that we didn't expect. And the  "**Selection... > Add Children to Selection**" won't consider this false child too.

2020-11-19 07:23 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-43f3ba5_22abf1c2.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-43f3ba5_22abf1c2.exe

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-43f3ba5_22abf1c2.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-43f3ba5.tar_22abf1c2.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-43f3ba5.tar_22abf1c2.gz

2020-11-19 19:10 UTC, ctrlaltdavid approved these changes

2020-11-19 20:21 UTC, kasenvr commented
According to QA it worked as expected: I created the zone entity and it doesn't show any children under it on the icon. Though, I didn't test any parenting as I was unsure what causes what in that respect.

2020-11-19 22:26 UTC, FluffyJenkins commented
@AleziaKurdis May I suggest making a tickbox to allow avatar/local entities to show up as children? (can be off by default which would equate to the functionality you are suggesting), Means that people who are creating complex avatars for example.

2020-11-20 03:31 UTC, AleziaKurdis commented
Hmm... Can we use the create application to edit avatar entities?

Because we can't for "Local" entities. They are not visible in the list and can't be selected.
To be able to create a local entity or set it a local entities as child of another entity, the only way is to do it using a script.

2020-11-20 03:33 UTC, kasenvr commented
We are able to adjust wearables with the Create App as far as I know.

2020-11-20 03:53 UTC, AleziaKurdis commented
We will put this PR on HOLD.
I will change the strategy.
and figure to exclude those specific "tools" entities
instead of excluding local entities (and avatar entities)
Seems that eventually, Local entities could be visible like all the others.

2020-11-21 20:53 UTC, AleziaKurdis commented
Finally, I change the approach.
I exclude now only the Entity Shape Visualizer 
instead of systematically all the local entities (and the avatar entities by the same time)

So this will continue to work for all types of entities. (domain, local, avatar)

I still don't think it will be viable to have the local entities visible in the create Application
it might seriously complexify everything to be able to protect the selection tool to self-edit

If we do this, I suggest that we implement a property to have specific local entities to never be returned by the findEntities### methods, getChildrens, and certainly some others.

2020-11-21 20:54 UTC, AleziaKurdis commented
You can now remove the "**Do not Merge**" flag and gives this to QA.

2020-11-21 22:15 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-4b9bf94_b633bc4a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-4b9bf94.tar_b633bc4a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-4b9bf94_b633bc4a.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-4b9bf94.tar_b633bc4a.Z

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-4b9bf94_b633bc4a.exe

2020-11-22 01:03 UTC, ctrlaltdavid requested changes

2020-11-22 01:03 UTC, ctrlaltdavid commented on scripts/system/create/edit.js
> +        if (properties.name !== entityShapeVisualizerSessionName && properties.name !== undefined) {
```suggestion
        if (properties.name !== undefined && properties.name !== entityShapeVisualizerSessionName) {
```
Thought it doesn't matter in this code, I suggest testing against `undefined` first, just as a matter of good habit.

2020-11-22 03:12 UTC, ctrlaltdavid approved these changes

2020-11-22 04:39 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-6b2ea04_343ded8c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-6b2ea04.tar_343ded8c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-6b2ea04.tar_343ded8c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-6b2ea04_343ded8c.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR874/Vircadia-Alpha-PR874-6b2ea04_343ded8c.exe

2020-11-24 23:09 UTC, Aitolda commented
Seems to be working as expected now.

2020-11-25 00:37 UTC, kasenvr approved these changes
Works fine for me as well.

2020-11-28 19:19 UTC, merged