Initial add of crash report arg option.
kasenvr/project-athena pull request #879
Opened 2020-11-21 19:50 UTC by kasenvr

Use the --forceCrashReporting command line parameter to have the crash handler launch regardless of what the internal setting says.

2020-11-21 21:41 UTC, vircadia-build-notifier commented
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-8f05bed_f7b0437b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-8f05bed.tar_f7b0437b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-8f05bed.tar_f7b0437b.Z

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-8f05bed_f7b0437b.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-8f05bed_f7b0437b.exe

2020-11-22 20:07 UTC, ctrlaltdavid requested changes

2020-11-22 20:07 UTC, ctrlaltdavid commented on interface/src/main.cpp
> +    if (forceCrashReporting || ual.isCrashMonitorEnabled()) {
```suggestion
    bool isCrashHandlerEnabled = ual.isCrashMonitorEnabled() || parser.isSet(forceCrashReportingOption);
    qDebug() << "Crash handler logger is enabled:" << isCrashHandlerEnabled;
    if (isCrashHandlerEnabled) {
```

2020-11-25 23:19 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-0b183d4_9b253c3a.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-0b183d4.tar_9b253c3a.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-0b183d4.tar_9b253c3a.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-0b183d4_9b253c3a.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-0b183d4_9b253c3a.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Alpha-PR879-0b183d4_9b253c3a.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR879/Vircadia-Quest-Alpha-PR879-0b183d4_9b253c3a.apk

2020-11-27 18:52 UTC, ctrlaltdavid approved these changes

2020-12-03 22:44 UTC, daleglass approved these changes

2020-12-03 22:46 UTC, merged